// A list of our compliments
var compliments = [
  "You’re talented.",
  "You have great dreams.",
  "You’re intelligent.",
  "You’re interesting.",
  "I’m so glad you’re mine.",
  "You have great ideas.",
  "You make me so proud.",
  "You win me over every day.",
  "You’re so special.",
  "I’m so lucky to have you.",
  "You’re fun.",
  "You’re smart.",
  "You’re beautiful.",
  "You’re handsome.",
  "You are such a blessing to me.",
  "You’re creative.",
  "You’re helpful.",
  "You’re inspiring.",
  "You love me well.",
  "You’re fantastic.",
  "You’re athletic.",
  "You’re artistic.",
  "You color my world.",
  "You encourage me.",
  "You’re the light of my life.",
  "You’re one of a kind.",
  "You have my heart.",
  "You’re delightful.",
  "You’re kind.",
  "I believe in you.",
  "You’re so trustworthy.",
  "You’re unique.",
  "You’re compassionate.",
  "You can do anything you put your mind to.",
  "You’re incredible.",
  "I love your laugh.",
  "You make my days sweeter.",
  "You make me smile.",
  "I love your smile.",
  "There’s no one else like you.",
  "You are a joy.",
  "I love that you belong to me.",
  "You’re thoughtful.",
  "You are excellent.",
  "You’re a great big brother/sister.",
  "You’re a great little brother/sister.",
  "My favorite time is time with you.",
  "I value you.",
  "You are worth so much to me.",
  "I love when you confide in me.",
  "You’re so strong.",
  "You’re the best.",
  "You rock.",
  "We make a great team.",
  "You do things with excellence.",
  "Nothing will ever keep me from loving you.",
  "I love being on your side.",
  "You’re a great leader.",
  "You make a difference.",
  "You matter to me.",
  "You’re so fun to play with.",
  "You always make me laugh.",
  "You are a great student.",
  "You’re radiant.",
  "You shine everyday.",
  "I love how you’re so truthful.",
  "You brighten my life.",
  "You’re amazing.",
  "You’re awesome.",
  "You are a wonderful part of our family.",
  "You make memories sweeter.",
  "You’re so respectful.",
  "You have incredible insight.",
  "You’re so hopeful.",
  "You’re positive.",
  "You love your friends well.",
  "I admire how you keep promises.",
  "You are such a leader at school.",
  "You’re a team player.",
  "I love that you never give up.",
  "You set a great example.",
  "You’re tremendous.",
  "You impact me everyday.",
  "You’re so fun-loving.",
  "You’re nice to others.",
  "You’re outstanding.",
  "You’re so refreshing.",
  "You put others first.",
  "I have confidence in you.",
  "I enjoy you.",
  "You’re marvelous.",
  "You make gray skies disappear.",
  "You’re doing great things.",
  "You’re unbelievable.",
];
